import Head from 'next/head'
import CandidateForm from '../components/candidate_form'
import { useEffect, useState } from 'react'
import getWeb3 from '../utils/getWeb3'
import VotingMachineContract from "../src/contracts/VotingMachine.json";
import CandidateList from '../components/candidate_list'

export default function Home() {
  const [web3, setWeb3] = useState(undefined);
  const [accounts, setAccounts] = useState([]);
  const [contract, setContract] = useState(null);

  useEffect(() => {
    async function setWeb3State() {
      const web3: any = await getWeb3();
      const accounts = await web3.eth.getAccounts();

      const networkId = await web3.eth.net.getId();
      const deployedNetwork = (VotingMachineContract as any).networks[networkId];
      const instance = new web3.eth.Contract(
        VotingMachineContract.abi,
        deployedNetwork && deployedNetwork.address,
      );

      setWeb3(web3);
      setAccounts(accounts);
      setContract(instance);
    }

    try {
      setWeb3State()
    } catch (error) {
      alert(
        `Failed to load web3, accounts, or contract. Check console for details.`,
      );
      console.error(error);
    }
  });

  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <CandidateForm web3={web3} contract={contract} accounts={accounts} />
        <CandidateList web3={web3} contract={contract} accounts={accounts} />
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            dgigafox software
          </span>
        </a>
      </footer>
    </div>
  )
}
