import Head from 'next/head'
import CandidateForm from '../components/candidate_form'
import { useEffect, useState } from 'react'
import getWeb3 from '../utils/get_web3'
import VotingMachineContract from "../src/contracts/VotingMachine.json";
import CandidateList from '../components/candidate_list'
import Header from '../components/header';

export default function Home() {
  const [web3, setWeb3] = useState(undefined);
  const [accounts, setAccounts] = useState([]);
  const [contract, setContract] = useState(null);
  const [isOwner, setIsOwner] = useState(false);

  useEffect(() => {
    async function setWeb3State() {
      const web3: any = await getWeb3();
      web3.eth.handleRevert = true;
      const accounts = await web3.eth.getAccounts();

      const networkId = await web3.eth.net.getId();
      const deployedNetwork = (VotingMachineContract as any).networks[networkId];
      const contract = new web3.eth.Contract(
        VotingMachineContract.abi,
        deployedNetwork && deployedNetwork.address,
      );

      setWeb3(web3);
      setAccounts(accounts);
      setContract(contract);

      console.log({ accounts })
      contract && contract.methods.owner().call({ from: accounts[0] })
        .then((ownerAddress: string) => {
          console.log({ ownerAddress })
          setIsOwner(ownerAddress === accounts[0])
        })
    }

    try {
      setWeb3State()
    } catch (error) {
      alert(
        `Failed to load web3, accounts, or contract. Check console for details.`,
      );
      console.error(error);
    }
  });

  return (
    <div className="flex flex-col min-h-screen">
      <Head>
        <title>Smartermatic</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="p-4 flex-grow">
        <Header />
        {isOwner && <CandidateForm web3={web3} contract={contract} accounts={accounts} />}
        <CandidateList web3={web3} contract={contract} accounts={accounts} />
      </main>

      <footer className="p-6 flex justify-center">
        Powered by dgigafox software
      </footer>
    </div>
  )
}
